# Generated by Django 5.0.4 on 2024-04-24 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.CharField(default='Enter a description', max_length=1000),
        ),
        migrations.AddField(
            model_name='listings',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='type',
            field=models.CharField(default='OT', max_length=3, verbose_name=[('CD', 'Cd'), ('VN', 'Vinyl'), ('CS', 'Cassette'), ('DG', 'Digital'), ('OT', 'Other')]),
        ),
        migrations.AddField(
            model_name='listings',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
